//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "channel_comics_provider_subscription")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub channel_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub provider_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::channel::Entity",
        from = "Column::ChannelId",
        to = "super::channel::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Channel,
    #[sea_orm(
        belongs_to = "super::comics_provider::Entity",
        from = "Column::ProviderId",
        to = "super::comics_provider::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ComicsProvider,
}

impl Related<super::channel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Channel.def()
    }
}

impl Related<super::comics_provider::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ComicsProvider.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
