//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "comics_provider")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::channel_comics_provider_subscription::Entity")]
    ChannelComicsProviderSubscription,
}

impl Related<super::channel_comics_provider_subscription::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChannelComicsProviderSubscription.def()
    }
}

impl Related<super::channel::Entity> for Entity {
    fn to() -> RelationDef {
        super::channel_comics_provider_subscription::Relation::Channel.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::channel_comics_provider_subscription::Relation::ComicsProvider
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
